# Generated by Django 4.2.10 on 2025-12-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_driverprofile_user_delete_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='abstractuser',
            unique_together={('phone', 'role')},
        ),
    ]
