# Generated by Django 4.2.10 on 2025-12-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_abstractuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='status',
            field=models.CharField(choices=[('idle', 'Boʻsh'), ('online', 'Onlayn'), ('offline', 'Offline'), ('busy', 'Band'), ('active', 'Faol'), ('inactive', 'Faol emas')], default='idle', max_length=20),
        ),
    ]
