# Generated by Django 4.2.10 on 2025-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_abstractuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='status',
            field=models.CharField(choices=[('online', 'Onlayn'), ('offline', 'Offline'), ('busy', 'Band'), ('active', 'Faol'), ('inactive', 'Faol emas')], default='offline', max_length=20),
        ),
    ]
