# Generated by Django 4.2.10 on 2025-12-03 14:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('in_progress', 'In Progress'), ('success', 'Success'), ('cancel_client', 'Cancelled by Client'), ('cancel_worker', 'Cancelled by Worker')], default='stable', max_length=20)),
                ('client_is_finished', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
