# Generated by Django 4.2.10 on 2025-12-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_workers',
            field=models.ManyToManyField(blank=True, related_name='accepted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='finished_workers',
            field=models.ManyToManyField(blank=True, related_name='finished_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='notified_workers',
            field=models.ManyToManyField(blank=True, related_name='notified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_workers',
            field=models.ManyToManyField(blank=True, related_name='rejected_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
