# Generated by Django 4.2.10 on 2025-12-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_driver_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted_workers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished_workers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notified_workers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rejected_workers',
        ),
    ]
