# Generated by Django 4.2.10 on 2025-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_accepted_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
